# Generated by Django 6.0.1 on 2026-01-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
